[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Form submission settings
[build.environment]
  NETLIFY_FORMS_ALLOWED_ORIGINS = "*"

# Enable form notifications
[[plugins]]
  package = "netlify-plugin-form-submissions"
